FROM python:3

RUN apt update && apt install -y git pv libpq-dev

RUN git clone https://github.com/philipmat/discogs-xml2db /app
WORKDIR /app

RUN pip3 install -r requirements.txt
RUN pip3 install -r postgresql/requirements.txt

# Update postgres config to point to host.docker.internal instead of localhost
RUN sed -i .bak 's/127.0.0.1/host.docker.internal/' postgresql/postgresql.conf

COPY load_discogs_data.sh .
CMD bash load_discogs_data.sh